- app/src/network/cosmos/config.ts
- contracts/packages/protocol/src/offer.rs
https://linear.app/localmoney/issue/LOCAL-732/fix-query-offersbytypefiat
> fix: query offers by type and fiat.

- contracts/contracts/trade/src/contract.rs
> chore: replaces get_offer with load_offer

- contracts/contracts/trade/src/contract.rs
> fix: fund_escrow fund validation

- contracts/packages/protocol/src/hub_utils.rs
Task: LOCAL-724
Description: allow the update of the `HubConfig`.
> fix: allow hub config update.

- contracts/README.md
- contracts/contracts/trade/src/contract.rs
- contracts/packages/protocol/src/constants.rs
- contracts/packages/protocol/src/hub.rs
- contracts/packages/protocol/src/trade.rs
- integration-tests/index.js
Task: LOCAL-745
Description: implement fee distribution mechanism
> feat: fee distribution

- contracts/contracts/hub/src/contract.rs
- contracts/contracts/offer/src/contract.rs
- contracts/contracts/trade/src/contract.rs
- contracts/contracts/trading_incentives/src/contract.rs
- contracts/packages/protocol/src/errors.rs
- contracts/packages/protocol/src/guards.rs
- contracts/packages/protocol/src/hub_utils.rs
- contracts/packages/protocol/src/offer.rs
- contracts/packages/protocol/src/trade.rs
LOCAL-734 - Standardize Errors and Responses
> chore: standardize errors and responses

- app/src/App.vue
- app/src/ui/components/trades/TradeOpenItem.vue
- app/src/ui/style/elements.scss
task: local-749 
Small fix of the margins between open trades cards.
> fix: layout open trade

- app/src/components.d.ts
- app/src/ui/components/Header.vue
- app/src/ui/components/NavDesktop.vue
- app/src/ui/components/NavMobile.vue
- app/src/ui/components/commons/Modal.vue
- app/src/ui/components/commons/NotificationWidget.vue
- app/src/ui/components/commons/NotificationWidgetMobile.vue
- app/src/ui/components/offers/CreateOffer.vue
- app/src/ui/pages/Offers.vue
- app/src/ui/style/elements.scss
> feature: layout-notification

- app/src/ui/components/commons/Modal.vue
- app/src/ui/components/commons/NotificationWidget.vue
- app/src/ui/pages/Offers.vue
task: local-777
Fixes the notification icon appearing on top of the modal component.
> fix: z-index hierarchy

- app/src/network/cosmos/CosmosChain.ts
- app/src/stores/client.ts
- app/src/ui/pages/TradeDetail.vue
task: LOCAL-781
details:
- fix `open trade` redirect
- fix `Trade Detail` loading and error states
> fix: open trade redirect

- app/src/App.vue
- app/src/ui/components/arbitration/ListDisputes.vue
- app/src/ui/components/arbitration/OpenDisputeItem.vue
> fix: dispute card item

- app/src/stores/notification.ts
> fix: notification for arbitrators

- app/.env.sample
- app/package.json
- app/src/network/cosmos/config.ts
> setup local kujira server

- app/src/ui/components/offers/ExpandedOffer.vue
> fix: layout expandedOffer with telegram handle

- app/src/App.vue
- app/src/ui/components/NavDesktop.vue
- app/src/ui/components/NavMobile.vue
- app/src/ui/components/arbitration/ListDisputes.vue
- app/src/ui/components/arbitration/OpenDisputeItem.vue
- app/src/ui/components/trades/TradeHistoryItem.vue
- app/src/ui/pages/Trades.vue
> fix: arbitration layout adjustments

- app/src/components.d.ts
- app/src/ui/components/commons/IconTooltip.vue
- app/src/ui/components/offers/CreateOffer.vue
- app/src/ui/components/offers/ExpandedOffer.vue
- app/src/ui/components/tradeDetail/ChatboxStates.vue
- app/src/ui/pages/TradeDetail.vue
> fix: layout telegram handle part 2

- app/src/ui/pages/TradeDetail.vue
> fix: telegram arbitrator view

- app/src/shared.js
- app/src/ui/components/offers/CreateOffer.vue
- app/src/ui/components/offers/ExpandedOffer.vue
task: LOCAL-842
- Disable `Create Offer` if telegram handle field is empty
- Disable `Open Trade` if telegram handle field is empty
> Telegram handle input validation

- app/src/ui/components/Header.vue
- app/src/ui/components/HomeHero.vue
- app/src/ui/components/NavDesktop.vue
- app/src/ui/components/commons/Modal.vue
- app/src/ui/components/commons/ModalLoading.vue
- app/src/ui/components/offers/ListOffers.vue
- app/src/ui/pages/Arbitration.vue
- app/src/ui/pages/Offers.vue
- app/src/ui/pages/Trades.vue
- app/src/ui/style/pages.scss
task: local-858
Changes:
- Fixed layout on smaller viewport sizes
- Fixed Create Offer buttons hiding off screen
- Fixed navbar items breaking on smaller viewport sizes
- Made navbar fixed on scroll to be more accessible
> fix: layout fixes and improvements

- app/src/ui/components/Header.vue
- app/src/ui/components/HomeHero.vue
- app/src/ui/components/NavDesktop.vue
- app/src/ui/components/commons/Modal.vue
- app/src/ui/components/commons/ModalLoading.vue
- app/src/ui/components/offers/ListOffers.vue
- app/src/ui/pages/Arbitration.vue
- app/src/ui/pages/Offers.vue
- app/src/ui/pages/Trades.vue
- app/src/ui/style/pages.scss
Reverts Local-Money/localmoney#97
> Fix Modals

- app/src/ui/pages/TradeDetail.vue
> fix: Trade Detail decrypt seller and buyer contacts

- app/src/stores/client.ts
- app/src/ui/pages/TradeDetail.vue
- app/src/utils/crypto.ts
> fix: TradeDetail pooling

- app/src/shared.js
- app/src/ui/components/offers/CreateOffer.vue
- app/src/ui/components/offers/ExpandedOffer.vue
> fix: default user telegram handle

- app/src/ui/pages/TradeDetail.vue
> feat: current step indicator

- app/src/App.vue
- app/src/ui/components/tradeDetail/TradeAction.vue
- app/src/ui/components/tradeDetail/TradeActions.vue
- app/src/ui/pages/TradeDetail.vue
> fix: trade detail CTA

- app/src/App.vue
- app/src/ui/pages/TradeDetail.vue
- app/src/ui/style/elements.scss
> fix: timer layout adjustments

- app/src/shared.js
- app/src/stores/notification.ts
- app/src/types/components.interface.ts
- app/src/ui/components/tradeDetail/TradeActions.vue
- app/src/utils/validations.ts
- contracts/contracts/trade/src/contract.rs
- contracts/packages/protocol/src/guards.rs
- contracts/packages/protocol/src/trade.rs
> feat: Cancel and Refund

- contracts/contracts/price/src/contract.rs
- contracts/contracts/trade/src/contract.rs
> fix: prevent opening a trade with the same wallet

- app/tests/utils.ts
- contracts/contracts/hub/src/contract.rs
Task: LOCAL-915
Tx on Testnet to see the logs: https://finder.kujira.app/harpoon-4/tx/6B198B7BFB47CB9EB90BC0F6C1264B4301070DF75FD71B5F405F8AFA13E6A572
Piggyback: 
- Reorganized the order of the SubMsgs to be alphabetical.
> fix: add profile_addr in Hub::update_cfg logs.

- app/src/network/cosmos/CosmosChain.ts
- app/tests/utils.ts
- contracts/contracts/trade/src/contract.rs
- contracts/packages/protocol/src/trade.rs
task: LOCAL-733
HUB: kujira1nedpguh7cqc0f66vjr0p2d4h33dplm3dqegy8tqv4u2va87uut0sdageap
Description:
- Adjusts testsuit to use the `PRICE_ADDR` to instante hub in the testnet.
- Changes trades query to use only one query.
> fix: trade query

- app/jest.config.js
- app/tests/hub.spec.ts
- app/tests/price.spec.ts
- app/tests/sequencer.js
- app/tests/trade.spec.ts
- contracts/contracts/trade/src/contract.rs
- contracts/packages/protocol/src/errors.rs
TASK: LOCAL-920
`HUB=kujira1yywgdademl7zm8sgz0hkxmz99yn36lfe2c5787w2f3lqj2syn2hq48c9u2`
`yarn test -t price` will run only the price related tests.
> fix:  prevent creation of a trade when denom_final_price is zero

- app/tests/sequencer.js
- app/tests/utils.ts
- contracts/Cargo.lock
- contracts/contracts/hub/Cargo.toml
- contracts/contracts/hub/src/contract.rs
- contracts/contracts/hub/src/state.rs
- contracts/contracts/offer/Cargo.toml
- contracts/contracts/offer/src/contract.rs
- contracts/contracts/offer/src/state.rs
- contracts/contracts/price/Cargo.toml
- contracts/contracts/price/src/contract.rs
- contracts/contracts/price/src/test.rs
- contracts/contracts/profile/Cargo.toml
- contracts/contracts/profile/src/contract.rs
- contracts/contracts/trade/Cargo.toml
- contracts/contracts/trade/src/contract.rs
- contracts/contracts/trading_incentives/Cargo.toml
- contracts/contracts/trading_incentives/src/contract.rs
- contracts/contracts/trading_incentives/src/state.rs
- contracts/packages/protocol/Cargo.toml
- contracts/packages/protocol/examples/hub_schema.rs
- contracts/packages/protocol/examples/offer_schema.rs
- contracts/packages/protocol/examples/trade_schema.rs
- contracts/packages/protocol/examples/trading_incentives_schema.rs
task: LOCAL-914
Hub Addr: `kujira1swek8g9zpn7pct96u7m67lg0uz49ya6lczldvrjr9ne3dc9agaxqx9t56f`
Piggyback:
- Run price tests right after Hub or it will fail.
> chore: rename protocol from localterra to localmoney

- app/tests/utils.ts
- contracts/contracts/trade/src/contract.rs
- contracts/packages/protocol/src/constants.rs
- contracts/packages/protocol/src/hub.rs
task: LOCAL-883
Hub Addr: `kujira1retnw6jqqxsyfm0z08487kte9wvhf089usdy099867e2r5r26c4sfe973u`
Piggyback:
- Removed a few unused constants from the constants file.
> chore: moved arbitration_fee parameter to hub_cfg.

- app/src/components.d.ts
- app/src/ui/components/commons/BaseIcon.vue
- app/src/ui/components/tradeDetail/TradeAction.vue
- app/src/ui/components/tradeDetail/TradeActions.vue
- app/src/ui/style/tokens.scss
> feature: icon component

- app/src/shared.js
- app/src/ui/components/NavDesktop.vue
- app/src/ui/components/offers/CollapsedOffer.vue
- app/src/ui/components/offers/ExpandedOffer.vue
- app/src/ui/components/offers/ListOffers.vue
- app/src/ui/style/elements.scss
> fix: ui-adjustments

- app/src/network/cosmos/CosmosChain.ts
- app/src/types/components.interface.ts
- app/tests/fixtures/offers.json
- app/tests/pagination.spec.ts
- app/tests/trade.spec.ts
- app/tests/utils.ts
- contracts/contracts/trade/src/contract.rs
- contracts/packages/protocol/src/errors.rs
- contracts/packages/protocol/src/hub.rs
Task: LOCAL-952
Hub: kujira1dd4ymthx288x0mt8g9zr32gnx3ez4q3p3dkjp2arvmcufkrfdw3q9znqnw
> add trade limit min

- app/tests/configs.ts
- contracts/contracts/hub/src/contract.rs
- contracts/packages/protocol/src/constants.rs
- contracts/packages/protocol/src/errors.rs
> fix:  critical parameters of hub can be modified unrestricted

- app/src/network/Chain.ts
- app/src/network/cosmos/CosmosChain.ts
- app/src/stores/client.ts
- app/src/stores/notification.ts
- app/src/types/components.interface.ts
- app/src/ui/components/myOffers/ArchivedOfferItem.vue
- app/src/ui/components/offers/CollapsedOffer.vue
- app/src/ui/components/offers/ExpandedOffer.vue
- app/src/ui/components/tradeDetail/TradeActions.vue
- app/src/ui/pages/TradeDetail.vue
- app/src/utils/validations.ts
- app/tests/arbitration.spec.ts
- app/tests/pagination.spec.ts
- app/tests/trade.spec.ts
- contracts/contracts/trade/src/contract.rs
- contracts/packages/protocol/src/trade.rs
task: LOCAL-971
test:
- pagination: `yarn test -t 'setup|fees|price test|pagination'`
> fix:  trades potential denial of service 

- app/package.json
- app/src/ui/components/CurrencyInput.vue
- app/src/ui/components/offers/ExpandedOffer.vue
- app/yarn.lock
Task: LOCAL-896:
Please run `yarn install` before testing this branch.
> chore: adjusted inputs in expanded offer.

- app/tests/trade.spec.ts
- contracts/contracts/profile/src/contract.rs
- contracts/contracts/trade/src/contract.rs
- contracts/packages/protocol/src/profile.rs
- contracts/packages/protocol/src/trade.rs
task: LOCAL-992
hub: kujira1mwm340dpdtumtnu9pdm0vy89r66ymwhxtm28eamxwl0te5tq780qfnsekh
> fix: active trade count limit, should count only after "accept or fund" states

- app/src/ui/components/Header.vue
- app/src/ui/components/commons/BetaPopUp.vue
task: local-1011
---
- Update tag on header from "testnet" to "beta"
- Update content of the beta pop-up
> fix: small fixes

- app/src/ui/components/offers/CreateOffer.vue
> feature: add tooltip to market price

- app/src/network/cosmos/CosmosChain.ts
- app/src/ui/pages/TradeDetail.vue
> fix: fund_escrow fee calculation

- app/src/network/Chain.ts
- app/src/network/cosmos/CosmosChain.ts
- app/src/stores/client.ts
- app/src/ui/components/commons/WalletButton.vue
> feat: Keep wallet connected

- app/src/shared.js
- app/src/ui/components/offers/CollapsedOffer.vue
- app/src/ui/components/offers/ExpandedOffer.vue
> feature: change layout trade count

- app/src/ui/pages/TradeDetail.vue
> fix: error displaying platform fee in trade detail

- app/src/ui/components/HomeHero.vue
> fix: update litepaper link

- app/src/ui/components/offers/ExpandedOffer.vue
> fix: trade count icon on expandedOffer

- app/src/stores/notification.ts
- app/src/ui/components/commons/WalletButton.vue
> fix: notification storage

- app/public/data/makers.json
- app/src/config/beta.ts
- app/src/config/featureToggle.ts
- app/src/stores/client.ts
- app/src/ui/components/NavDesktop.vue
- app/src/ui/components/NavMobile.vue
- app/src/ui/pages/Offers.vue
> add more beta makers

- app/src/stores/client.ts
> fix: app header name

- app/src/network/cosmos/config/kujira.ts
task: LOCAL-1027
Description: 
- changes `rpc` and `lcd` from `setten` to `whispernode`.
> fix: rpc and lcd

- app/src/network/cosmos/config/kujira.ts
- app/src/ui/pages/TradeDetail.vue
> feature: localbot front

- app/src/ui/components/commons/WalletButton.vue
- app/src/ui/components/commons/WalletWidget.vue
> fix: wallet button and wallet widget

- app/src/analytics/analytics.ts
- app/src/routes.ts
- app/src/types/components.interface.ts
- app/src/ui/components/arbitration/ListDisputes.vue
- app/src/ui/components/arbitration/OpenDisputeItem.vue
- app/src/ui/components/myOffers/ArchivedOfferItem.vue
- app/src/ui/components/myOffers/CollapsedMyOffer.vue
- app/src/ui/components/myOffers/ExpandedMyOffer.vue
- app/src/ui/components/myOffers/ListMyOffers.vue
- app/src/ui/components/offers/CollapsedOffer.vue
- app/src/ui/components/offers/CreateOffer.vue
- app/src/ui/components/offers/ExpandedOffer.vue
- app/src/ui/components/offers/ListOffers.vue
- app/src/ui/components/trades/TradeHistoryItem.vue
- app/src/ui/components/trades/TradeOpenItem.vue
- app/src/ui/pages/TradeDetail.vue
- app/src/ui/pages/Trades.vue
- app/src/utils/denom.ts
- app/src/utils/denoms-config.json
- app/src/utils/validations.ts
task: LOCAL-1101
description:
- uses LocalStorage to persist offers filtering in `ListOffers` and `CreateOffer`
- add configuration to allow filtering of offers via link.
- improves `utils/denom.ts`
> feature: persist offers filtering

- app/src/ui/components/offers/CreateOffer.vue
- app/src/ui/components/offers/ListOffers.vue
- app/src/utils/denoms-config.json
description:
- adds `axlUSDC`
- sets `axlUSDC` and `USD` as default offer list filter.
> feat: add axlUSDC
